name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.0.2
homepage: https://github.com/anicdh
author: andoan <anic.dh@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bip39: ^1.0.6
  bip32: ^1.0.10
  pointycastle: ^3.0.1
  hex: ^0.2.0
  bs58check: ^1.0.2
  meta: ^1.3.0
  bech32: 0.2.0

dev_dependencies:
  test: ^1.15.4
